### PR TITLE
remove winapi dependency, upgrade edition and replace decrypted APIs

### PR DESCRIPTION
**Pull request by sn99**
I am attempting to update the codebase to utilize [`windows-rs`](https://github.com/microsoft/windows-rs) instead of `winapi`. While the build is successful, 1 test is currently failing with the error message ``thread 'test_load_appkey' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }', tests\reg_key.rs:45:77``.

### CODE REVIEW

**Comment by poliorcetics** [comment]
Hey @sn99, are you still working on this ?

**Comment by sn99** [comment]
@poliorcetics I think this was about done, the test failed even before I made any changes so doesn't really seem that there was anything to work on

**Comment by poliorcetics** [comment]
There are conflicts now though, maybe the test has been fixed since then ?

**Comment by gentoo90** [comment]
Rebased onto the latest `master` and published as part of version [`0.50.0`](https://crates.io/crates/winreg/0.50.0)

**Pull request closed without merging**
